BEGIN;

CREATE TYPE types AS ENUM (
  'breakfast',
  'lunch',
  'dinner',
  'snack'
);

CREATE TABLE recipes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  category TEXT,
  type types
);

COMMIT;